services:
  - type: web
    name: vexel-store-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: VOUCH_CHANNEL_ID
        sync: false
      - key: AUTO_REACT_CHANNEL_ID
        sync: false
      - key: PAYMENT_PING_ROLE_ID
        sync: false
      - key: PROTECTED_ROLE_IDS
        sync: false
      - key: CASHAPP_TAG
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: VERIFIED_ROLE_ID
        sync: false
      - key: UNVERIFIED_ROLE_ID
        sync: false
      - key: VERIFY_CHANNEL_ID
        sync: false
  - type: web
    name: botivo-ticket-bot
    runtime: node
    plan: free
    rootDir: ticket-bot
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false
      - key: SUPPORT_ROLE_ID
        sync: false
      - key: TICKET_CATEGORY_ID
        sync: false
      - key: TICKET_LOG_CHANNEL_ID
        sync: false
      - key: PANEL_CHANNEL_ID
        sync: false
      - key: WEBSITE_URL
        sync: false
